version: '3'
services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d/sites-available:/etc/nginx/conf.d/sites-available"
      - "./nginx/conf.d/sites-enabled:/etc/nginx/conf.d/sites-enabled"
  container1:
    container_name: container1
    hostname: container1
    image: example1:latest
    ports:
      - '8081:8080'
  container2:
    container_name: container2
    hostname: container2
    image: example2:latest
    ports:
      - '8082:8080'
  container3:
    container_name: container3
    hostname: container3
    image: example3:latest
    ports:
      - '8083:8080'
